### ISSUE TITLE
discord minesweeper generator feature requests

### ISSUE THREAD

**Issue by eksynn** [pfgithub/sitepages#1]
could we have two new features added to your minesweeper generator?  
one: the ability to save the custom fields and import them again when needed
two: a character counter, which warns us when the code goes over 2k characters

also the ability to automatically replace the dot at the start with a ">>> "

thank you in advance! hope this is still being developed and updated ( ◠ ‿◠)
also thank you for making this, it's very handy. my server and i have a lot of fun with this.

**Comment by pfgithub** [comment]
ok I rewrote the generator and added the ability to save customizations, added a character counter, and made the starting dot configurable. also, bombs are now a percentage instead of a number.

also I have a bot which makes these automatically, but isn't as configurable. https://interpunct.info ([invite link](https://discord.com/oauth2/authorize?client_id=433078185555656705&permissions=3072&scope=bot))

the `ip!minesweeper` command makes minesweeper games like this:
![image](https://user-images.githubusercontent.com/6010774/90344130-8d49ca80-dfcb-11ea-96df-644601e4a819.png)
the top left is cleared automatically (because it's always safe), and it supports sizes up to 25x25 even if they go over the character limit. it also has a few other games: `ip!connect4`, `ip!tictactoe`, `ip!circlegame`, `ip!ultimate tictactoe`, and a few more
